name: All API Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  API_Tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run Tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="testCases.GetAllCompanies.*,
          testCases.GetPostDetails.*,
          testCases.GetToDoListDetails.*,
          testCases.GetUserDetailsByID.*"

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: API_Tests_Allure_Report
          path: "allure-report/*_AllureReport.html"

      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: API_Tests_Summery_Report
          path: "execution-summary/ExecutionSummaryReport_*.html"

      - name: Publish Test Results
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          check_name: "Tests Results API Tests"
          files: |
            target/surefire-reports/TEST-*.xml